### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by swervx** [Gozzim/mod-npc-spectator#5]
Hello, do you have an update for this mod ?

![Capture d’écran 2022-04-06 033957](https://user-images.githubusercontent.com/101983666/161878533-d58898e4-b2c7-42c9-af81-f0e02b5cab0f.png)

**Comment by Gozzim** [comment]
I will have a look today to update the mod to work with the newest version :)
Thanks for the information

**Comment by Gozzim** [comment]
Pushed a fix in 377923fcad73181bba2778bf75e41d843b02a40a
I'm happy for any tests and bug reports
